fixes

diff --git a/bash/stop b/bash/stop
--- a/bash/stop
+++ b/bash/stop
@@ -1,15 +1,31 @@
 #!/bin/bash
 
+function success() {
+  echo "ok"
+}
+
+function failure() {
+  echo "FAILED ($@)"
+  exit 1
+}
+
 if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
   git reset --hard HEAD 1>/dev/null 2>&1
   git pull -f 1>/dev/null 2>&1
 fi
 
 echo "Checking Requirements:"
+
+echo -n "docker is running    .. " 
+[ "$(docker info --format '{{ .ServerErrors }}')" == "[]" ] && success || fialure "is docker running?"
+
+echo -n "docker 19+           .. "
+[ "$(docker info --format '{{ .ServerVersion }}' | cut -d. -f1)" -ge 19 ] && success || failure "should be 19+"
+
+echo -n "docker-compose       .. "
 DOCKER_COMPOSE_VERSION=$(docker-compose --version | sed -E 's/.*([0-9]{1,2}.[0-9]{2}.[0-9]+),.*/\1/' | cut -d. -f2)
-[ "$(docker info --format '{{ .ServerErrors }}')" == "[]" ] && printf "%-20s .. ok\n" "docker is running" || printf "%-20s .. %s\n" "docker is running" "FAILED (is docker running?)" && exit 1
-[ "$(docker info --format '{{ .ServerVersion }}' | cut -d. -f1)" -ge 19 ] && printf "%-20s .. ok\n" "docker" || printf "%-20s .. %s\n" "docker" "FAILED (should be 19+)" && exit 1
-[ "${DOCKER_COMPOSE_VERSION:-0}" -ge 25 ] && printf "%-20s .. ok\n" "docker-compose" || printf "%-20s .. %s\n" "docker-compose" "FAILED (should be 1.25+)" && exit 1
+[ "${DOCKER_COMPOSE_VERSION:-0}" -ge 25 ] && success || failure "should be 1.25+" 
+
 echo
 
 ## Removing previous stack, if it is
